// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadDoubanCover(arg1) {
  return window['go']['main']['App']['DownloadDoubanCover'](arg1);
}

export function DownloadDoubanCoverPreview(arg1) {
  return window['go']['main']['App']['DownloadDoubanCoverPreview'](arg1);
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RunBackend(arg1) {
  return window['go']['main']['App']['RunBackend'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SearchDoubanCover(arg1) {
  return window['go']['main']['App']['SearchDoubanCover'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function SelectTxtFile() {
  return window['go']['main']['App']['SelectTxtFile']();
}
