// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadDoubanCover(arg1:string):Promise<string>;

export function DownloadDoubanCoverPreview(arg1:string):Promise<string>;

export function GetLogFilePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenLogFile():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RunBackend(arg1:Array<string>):Promise<main.BackendResult>;

export function SaveFile(arg1:string):Promise<string>;

export function SearchDoubanCover(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFiles(arg1:Record<string, any>):Promise<Array<string>>;

export function SelectTxtFile():Promise<string>;
